JIRA_HOME=https://aexis-medical.atlassian.net
JIRA_EMAIL=KHettiarachchi@Aexis-Medical.com
JIRA_TOKEN=ATATT3xFfGF02WAaX43OH6h4syfdB5JF2yMxcOePw3cfnpMVlmFGu35DAOZzG1OohIUOeF1x2_7KUi5z8Z-0uhCAJwmWaHygfdkb2_VQRe0vapEBmxc0f7jMK374bWTiZtRCREA9H-z1NH0fAJnJIN4RD4wsERL3gxgkRJHQJo_JdIj_HnBHEXk=31A07FD9
JIRA_PROJECTS=Requirement,Testing
JIRA_PROJECT_ROOTS=REQ-100,TST-1